name: Generate Snake Animation üêç

on:
  schedule:
    - cron: "0 */12 * * *" # –æ–±–Ω–æ–≤–ª—è–µ—Ç—Å—è –∫–∞–∂–¥—ã–µ 12 —á–∞—Å–æ–≤
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Generate snake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Belassov
          outputs: dist/snake.svg
          # üé® –ù–∞—Å—Ç—Ä–æ–π–∫–∞ —Ü–≤–µ—Ç–æ–≤
          # –º–æ–∂–Ω–æ –ø–æ–∏–≥—Ä–∞—Ç—å —Å —Ñ–æ–Ω–æ–º –∏ —Ü–≤–µ—Ç–∞–º–∏ –¥–ª—è –Ω—É–∂–Ω–æ–≥–æ —Å—Ç–∏–ª—è
          color_snake: "#00FFB3"
          color_dots: "#3B3B3B,#2E2E2E,#242424,#1A1A1A,#141414"
          color_bg: "#1E1E2E" # —Ç—ë–º–Ω–æ-—Å–µ—Ä—ã–π —Å —Ñ–∏–æ–ª–µ—Ç–æ–≤—ã–º –ø–æ–¥—Ç–æ–Ω–æ–º, –Ω–µ —Å–ª–∏–≤–∞–µ—Ç—Å—è —Å GitHub dark theme

      - name: Push snake animation to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
